- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Text\TextController
    title: Fancy Text
    groupId: features
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
        lifetime: 60 seconds
    propertyGroups:
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: layout
          type: top
          label: Layout
          icon: /cms/lib/supra/img/toolbar/icon-layout.png
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: design
          type: top
          label: Design
          icon: /cms/lib/supra/img/toolbar/icon-design.png
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content
          editable: Supra\Editable\Html
          label: Content
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_2
          editable: Supra\Editable\Html
          label: Content 2
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_3
          editable: Supra\Editable\Html
          label: Content 3
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_4
          editable: Supra\Editable\Html
          label: Content 4
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: background_image
          group: design
          editable: Supra\Editable\BlockBackground
          label: Background image
          properties:
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: image
                editable: Supra\Editable\Image
                label: Image (nonono)
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: classname
                editable: Supra\Editable\String
                label: Pattern (nonono)
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: background_color
          group: design
          editable: Supra\Editable\Color
          label: Background color
          additionalParameters:
            allowUnset: true
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: border_style
          group: design
          editable: Supra\Editable\SelectVisual
          label: Border style
          values:
            - id: border-none
              title: None
              icon: icons/border-none.png
            - id: border-thin
              title: Thin line
              icon: icons/border-thin-line.png
            - id: border-medium
              title: Medium line
              icon: icons/border-medium-line.png
            - id: border-thick
              title: Thick line
              icon: icons/border-thick-line.png
            - id: border-rounded
              title: Rounded corners
              icon: icons/border-rounded.png
            - id: border-dashed
              title: Dashed line
              icon: icons/border-dashed.png
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: border_color
          group: design
          editable: Supra\Editable\Color
          label: Border color
          additionalParameters:
            allowUnset: true
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: layout
          group: layout
          editable: Supra\Editable\SelectVisual
          label: Layout
          values:
            - id: column_1
              title: 1 column
              html: <table><tr><td class="h-2 w-12">1</td></tr></table>
            - id: column_2
              title: 2 columns
              html: <table><tr><td class="h-2 w-6">1</td><td class="h-2 w-2">2</td></tr></table>
            - id: column_3
              title: 3 columns
              html: <table><tr><td class="h-2 w-4">1</td><td class="h-2 w-4">2</td><td class="h-2 w-4">3</td></tr></table>
            - id: column_4
              title: 4 columns
              html: <table><tr><td class="h-2 w-3">1</td><td class="h-2 w-3">2</td><td class="h-2 w-3">3</td><td class="h-2 w-3">4</td></tr></table>
            - id: column_1_2_h
              title: 1+2 columns
              html: <table><tr><td class="h-2 w-6" rowspan="2">1</td><td class="h-1 w-4">2</td></tr><tr><td class="h-1 w-4">3</td></tr></table>
            - id: column_2_1_h
              title: 2+1 columns
              html: <table><tr><td class="h-1 w-4">1</td><td class="h-2 w-6" rowspan="2">3</td></tr><tr><td class="h-1 w-4">2</td></tr></table>
            - id: column_2_1_v
              title: 3 columns
              html: <table><tr><td class="h-2 w-6">1</td><td class="h-2 w-3">2</td><td class="h-2 w-3">3</td></tr></table>
            - id: column_1_2_v
              title: 3 columns
              html: <table><tr><td class="h-2 w-3">1</td><td class="h-2 w-3">2</td><td class="h-2 w-6">3</td></tr></table>
          additionalParameters:
            iconStyle: html
            style: mid
            css: |
              .su-button .su-button-bg { padding: 0; }
              .su-button .su-button-bg div { height: 57px; }
              table { width: 100%; border-spacing: 3px; border-collapse: separate; }
              td { 
              background: url(/components/FancyBlocks/Text/icons/background.png) 0 0 repeat-x;
              vertical-align: middle; text-align: center;
              text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.6), 0 1px 0 rgba(255, 255, 255, 0.5);
              color: #054873;
              font-size: 18px;
              font-weight: bold;
              }
              td.h-1 { height: 24px; background-position: 0 -52px; }
              tr + tr td.h-1 { height: 24px; background-position: 0 -77px; }
              td.h-2 { height: 52px; font-size: 30px; }
              td.w-12 { width: 100%; }
              td.w-6 { width: 50%; }
              td.w-4 { width: 33.3%; }
              td.w-3 { width: 25%; }
