- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Text\TextController
    title: Text
    groupId: features
    description: Allows you to enter and manage text. Look into the block settings for several view options – select a standard view or chose from several promo boxes.
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
    propertyGroups:
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: layout
          type: top
          label: Layout
          icon: /cms/lib/supra/img/toolbar/icon-layout.png
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: design
          type: top
          label: Design
          icon: /cms/lib/supra/img/toolbar/icon-design.png
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content
          editable: Supra\Editable\Html
          label: Content
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_2
          editable: Supra\Editable\Html
          label: Content 2
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_3
          editable: Supra\Editable\Html
          label: Content 3
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_4
          editable: Supra\Editable\Html
          label: Content 4
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: background_image
          group: design
          editable: Supra\Editable\BlockBackground
          label: Background image
          properties:
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: image
                editable: Supra\Editable\Image
                label: Image (nonono)
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: classname
                editable: Supra\Editable\String
                label: Pattern (nonono)
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: background_color
          group: design
          editable: Supra\Editable\Color
          label: Background color
          additionalParameters:
            allowUnset: true
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: border_style
          group: design
          editable: Supra\Editable\SelectVisual
          label: Border style
          values:
            - id: border-none
              title: None
              icon: icons/border-none.png
            - id: border-thin
              title: Thin line
              icon: icons/border-thin-line.png
            - id: border-medium
              title: Medium line
              icon: icons/border-medium-line.png
            - id: border-thick
              title: Thick line
              icon: icons/border-thick-line.png
            - id: border-rounded
              title: Rounded corners
              icon: icons/border-rounded.png
            - id: border-dashed
              title: Dashed line
              icon: icons/border-dashed.png
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: border_color
          group: design
          editable: Supra\Editable\Color
          label: Border color
          additionalParameters:
            allowUnset: true
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: layout
          group: layout
          editable: Supra\Editable\SelectVisual
          label: Layout
          values:
            - id: column_1
              title: 1 column
              html: <table><tr><td class="h-2 w-12">4</td></tr></table>
            - id: column_2
              title: 2 columns
              html: <table><tr><td class="h-2 w-6">2</td><td class="h-2 w-2">2</td></tr></table>
            - id: column_3
              title: 3 columns
              html: <table><tr><td class="h-2 w-4">1</td><td class="h-2 w-4">1</td><td class="h-2 w-4">1</td></tr></table>
            - id: column_4
              title: 4 columns
              html: <table><tr><td class="h-2 w-3">1</td><td class="h-2 w-3">1</td><td class="h-2 w-3">1</td><td class="h-2 w-3">1</td></tr></table>
            - id: column_1_2_h
              title: 1+2 columns
              html: <table><tr><td class="h-2 w-6" rowspan="2">2</td><td class="h-1 w-6">2</td></tr><tr><td class="h-1 w-6">2</td></tr></table>
            - id: column_2_1_h
              title: 2+1 columns
              html: <table><tr><td class="h-1 w-6">2</td><td class="h-2 w-6" rowspan="2">2</td></tr><tr><td class="h-1 w-6">2</td></tr></table>
            - id: column_2_1_v
              title: 3 columns
              html: <table><tr><td class="h-2 w-6">2</td><td class="h-2 w-3">1</td><td class="h-2 w-3">1</td></tr></table>
            - id: column_1_2_v
              title: 3 columns
              html: <table><tr><td class="h-2 w-3">1</td><td class="h-2 w-3">1</td><td class="h-2 w-6">2</td></tr></table>
          additionalParameters:
            iconStyle: html
            style: mid
            css: |
              .su-button .su-button-bg { padding: 0; }
              .su-button .su-button-bg div { height: 57px; }
              table { width: 100%; border-spacing: 3px; border-collapse: separate; }
              td { 
              background: url(/components/FancyBlocks/Text/icons/background.png) 0 -102px repeat-x;
              vertical-align: middle; text-align: center;
              text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.6), 0 1px 0 rgba(255, 255, 255, 0.5);
              color: #4b4e62;
              font-size: 18px;
              font-weight: bold;
              }
              td.h-1 { height: 24px; background-position: 0 -154px; }
              tr + tr td.h-1 { height: 24px; background-position: 0 -179px; }
              td.h-2 { height: 52px; font-size: 30px; }
              td.w-12 { width: 100%; }
              td.w-6 { width: 50%; }
              td.w-4 { width: 33.3%; }
              td.w-3 { width: 25%; }
              .su-button-down td,
              .su-button-mouse-hover td { color: #054873; background-position: 0 0; }
              .su-button-down td.h-1,
              .su-button-mouse-hover td.h-1 { background-position: 0 -52px; }
              .su-button-down tr + tr td.h-1,
              .su-button-mouse-hover tr + tr td.h-1 { background-position: 0 -77px; }
