- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\BlogPostListShort\BlogPostListShortBlock
    title: Latest posts 
    groupId: blog
    description: Displays a short
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
        lifetime: 60 seconds
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Blog
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: blog_page
          editable: Supra\Editable\Link
          label: Blog page
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: posts_per_page
          editable: Supra\Editable\Number
          label: Posts per page
          default: 3
          additionalParameters:
            minValue: 1
            # some reasonable value should be placed here
            maxValue: 25