- Supra\Router\Configuration\RouterConfiguration:
    url: /social
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Project\SocialMedia\SocialMediaController