- _use: Supra\Controller\Pages\Configuration\SerializablePropertyConfiguration
- _use: Supra\Controller\Pages\MediaGallery\MediaGalleryLayoutConfiguration

- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\GalleryAdvanced\GalleryAdvancedBlock
    title: Media gallery
    icon: icon.png
    groupId: features
    description: Show images, videos and text elements.
    cmsClassname: MediaGallery
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: false
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
          
    propertyGroups:
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: columns
          icon: /cms/lib/supra/img/sidebar/icons/button-layout.png
          label: Layout
          
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Media
          
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: columns
          group: columns
          editable: Supra\Editable\SelectVisual
          label: Layout
          default: columns_2
          values:
            - id: columns_1
              title: 1 column
              html: <table><tr><td class="h-2 w-12">1</td></tr></table>
            - id: columns_2
              title: 2 columns
              html: <table><tr><td class="h-2 w-6">1</td><td class="h-2 w-2">2</td></tr></table>
            - id: columns_3
              title: 3 columns
              html: <table><tr><td class="h-2 w-4">1</td><td class="h-2 w-4">2</td><td class="h-2 w-4">3</td></tr></table>
            - id: columns_4
              title: 4 columns
              html: <table><tr><td class="h-2 w-3">1</td><td class="h-2 w-3">2</td><td class="h-2 w-3">3</td><td class="h-2 w-3">4</td></tr></table>
          additionalParameters:
            iconStyle: html
            style: mid
            css: |
              .su-button .su-button-bg { padding: 0; }
              .su-button .su-button-bg div { height: 57px; }
              table { width: 100%; border-spacing: 3px; border-collapse: separate; }
              td { 
              background: url(/components/FancyBlocks/Text/icons/background.png) 0 -102px repeat-x;
              vertical-align: middle; text-align: center;
              text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.6), 0 1px 0 rgba(255, 255, 255, 0.5);
              color: #4b4e62;
              font-size: 18px;
              font-weight: bold;
              }
              td.h-1 { height: 24px; background-position: 0 -154px; }
              tr + tr td.h-1 { height: 24px; background-position: 0 -179px; }
              td.h-2 { height: 52px; font-size: 30px; }
              td.w-6 { width: 50%; }
              td.w-4 { width: 33.3%; }
              td.w-3 { width: 25%; }
              .su-button-down td,
              .su-button-mouse-hover td { color: #054873; background-position: 0 0; }
              .su-button-down td.h-1,
              .su-button-mouse-hover td.h-1 { background-position: 0 -52px; }
              .su-button-down tr + tr td.h-1,
              .su-button-mouse-hover tr + tr td.h-1 { background-position: 0 -77px; }
          
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: media
          label: Media items
          editable: Supra\Editable\MediaGallery                  
          properties:
            - SerializablePropertyConfiguration:
                name: layout
                editable: Supra\Editable\Hidden
                label: layout
            - SerializablePropertyConfiguration:
                name: title
                editable: Supra\Editable\InlineString
                label: Title
                default: Title
            - SerializablePropertyConfiguration:
                name: text
                editable: Supra\Editable\Html
                label: Text
                default: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed cursus, sapien ac rhoncus suscipit, enim ligula laoreet arcu, eget tempus mauris nisi vel lacus.</p>
            - SerializablePropertyConfiguration:
                name: image
                label: Image
                editable: Supra\Editable\InlineMedia
                additionalParameters:
                  allowVideo: false
            - SerializablePropertyConfiguration:
                name: video
                label: Video
                editable: Supra\Editable\InlineMedia
                additionalParameters:
                  allowImage: false
            - SerializablePropertyConfiguration:
                name: link
                editable: Supra\Editable\Link
                label: Link
            - SerializablePropertyConfiguration:
                name: link_title
                editable: Supra\Editable\String
                label: Link title
                default: Visit site
          additionalParameters:
            layouts:
              - MediaGalleryLayoutConfiguration: 
                  name: video
                  file: templates/video.html.twig
              - MediaGalleryLayoutConfiguration: 
                  name: image
                  file: templates/image.html.twig
              - MediaGalleryLayoutConfiguration: 
                  name: text
                  file: templates/text.html.twig
            separateSlide: false