- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Gallery\GalleryBlock
    title: Gallery
    groupId: features
    description: Description
    cmsClassname: Gallery
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Gallery
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: images
          editable: Supra\Editable\Gallery
          label: Images
          properties:
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: title
                editable: Supra\Editable\String
                label: Title
                default: Lorem ipsum dolor sit amet
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: description
                editable: Supra\Editable\Textarea
                label: Description
                default: Volutpat nunc aliquet amet duis duis ultrices egestas ac ipsum sit arcu ac sagittis consectetur id adipiscing eu
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: style
          editable: Supra\Editable\SelectVisual
          label: Style
          default: grid
          values:
            - id: grid
              title: Grid with lightbox
              icon: icons/style-grid.png
            - id: slideshow
              title: Slideshow
              icon: icons/style-slideshow.png
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: design
          editable: Supra\Editable\SelectVisual
          label: Design
          default: simple
          values:
            - id: simple
              title: Plain
              icon: icons/design-simple.png
            - id: border
              title: Frame
              icon: icons/design-border.png
            - id: box
              title: Shadow
              icon: icons/design-boxes.png