- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\BlogPostList\BlogPostListBlock
    title: Blog roll
    groupId: blog
    description: A list of blog posts. Designed to be placed on the blog’s main page.
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
        context: [__blogListPage, __blogListTag, __blogArchivePeriod]
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Blog
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: previous_page
          editable: Supra\Editable\String
          label: Previous page label
          default: Previous page
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: next_page
          editable: Supra\Editable\String
          label: Next page label
          default: Next page
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: posts_per_page
          editable: Supra\Editable\Number
          label: Posts per page
          default: 5
          additionalParameters:
            minValue: 1
            # some reasonable value should be placed here
            maxValue: 25
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: style
          editable: Supra\Editable\SelectVisual
          label: Style in post list
          default: promoted
          values:
            - id: normal
              title: Small thumbnail
              icon: icons/style-normal.png
            - id: promoted
              title: Full size image or video
              icon: icons/style-promoted.png
          additionalParameters:
            style: mid
            iconStyle: center