- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: News List
    groupId: system
    icon: news_menu.png
    class: Project\Blocks\NewsList\NewsListBlock
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: false
        groups:
          - Supra\Controller\Pages
        context:
          - breadcrumbs_year
