- _use: Supra\Controller\Pages\Plugin\HtmlInjection

- _class: HtmlInjection
  id: assets.js.jquery
  html:
    js: |
       <script src="/assets/js/jquery-1.7.2.min.js"></script>

- _class: HtmlInjection
  id: assets.js.app.app
  html:
    js: |
       <script src="/assets/js/app/app.js"></script>
  depends:
    - assets.js.jquery

- _class: HtmlInjection
  id: assets.js.app.parse
  html:
    js: |
      <script>
       $(function () {
         $.app.parse($('body'));
       });
      </script>
  depends:
    - assets.js.app.app

- _class: HtmlInjection
  id: assets.js.app.ajaxcontent
  html:
    js: |
      <script src="/assets/js/app/ajaxcontent.js"></script>
  depends:
    - assets.js.app.app
    - assets.js.app.parse

- _class: HtmlInjection
  id: assets.js.app.ajaxform
  html:
    js: |
      <script src="/assets/js/app/ajaxform.js"></script>
  depends:
    - assets.js.app.ajaxcontent

- _class: HtmlInjection
  id: assets.js.app.ajaxform.files
  html:
    js: |
      <script src="/assets/js/app/ajaxform-upload.js"></script>
  depends:
    - assets.js.app.ajaxform