- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    controllerClass: Project\Text\TextController
    title: Text
    groupId: system
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    cmsClassname: Editable