- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\SocialShare\SocialShareBlock
    title: Social share
    groupId: features
    description: Allows visitors to publish a link to the page in popular social networks.
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: share_title
          editable: Supra\Editable\InlineString
          label: Title
          default: Share This Story, Choose Your Platform!