# Group ordering depends on configuration position
#
# The "default" parameter means next
#
# 1) That group will be used by default if group id in block configuration file 
#    does not match any of group ids configured here
# 
# 2) That group will be selected by default in "Insert Block" view

- Supra\Controller\Pages\Configuration\BlockControllerGroupConfiguration:
    id: system
    title: System
    default: true

- Supra\Configuration\IncludeLoaderConfiguration:
    files:
      - ${__DIR__}/Blocks/config.yml
      - ${__DIR__}/AjaxContentBlock/config.yml
      - ${__DIR__}/AjaxPoll/config.yml
      - ${__DIR__}/Sitemap/config.yml
      - ${__DIR__}/FancyBlocks/NewsText/config.yml


- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: Transact data form
    groupId: system
    class: Project\Payment\Transact\TransactDataForm
    description: Transact data form
    cmsClassname: Editable
    
