# Group ordering depends on configuration position
#
# The "default" parameter means next
#
# 1) That group will be used by default if group id in block configuration file 
#    does not match any of group ids configured here
# 
# 2) That group will be selected by default in "Insert Block" view

- Supra\Controller\Pages\Configuration\BlockControllerGroupConfiguration:
    id: system
    title: System
    default: true
    
- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
   title: Broken block
   groupId: system
   controllerClass: Supra\Controller\Pages\BrokenBlockController