- _use: Supra\Controller\Pages\Configuration

- Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\BlogArchive\BlogArchiveBlock
    title: Blog archive
    icon: icon.png
    groupId: blog
    description: A side-menu that shows blog posts grouped by time period – months and years.
    cmsClassname: Editable   
    properties:
      - Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Archive
      - Configuration\BlockPropertyConfiguration:
          name: view_all_title
          editable: Supra\Editable\String
          label: View all
          default: View all archives
      - Configuration\BlockPropertyConfiguration:
          name: blog_page
          editable: Supra\Editable\Link
          label: Blog page