- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\GoogleMap\GoogleMapBlock
    title: Google Maps
    groupId: features
    description: Embed Google Maps into your pages. 
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Google Map
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: map
          editable: Supra\Editable\InlineMap
          label: Google Map
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: marker_text
          editable: Supra\Editable\Textarea
          label: Tooltip text
          description: Address or description which will be shown in tooltip
          default: Volutpat nunc aliquet amet duis duis ultrices egestas ac ipsum sit arcu ac sagittis consectetur id adipiscing eu
