- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\NewsText\NewsTextBlock
    title: News Text
    groupId: features
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
        lifetime: 60 seconds
    propertyGroups:
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: layout
          type: top
          label: Layout
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: description
          editable: Supra\Editable\Textarea
          label: Short description
          default: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: image
          editable: Supra\Editable\Image
          label: Image
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content
          editable: Supra\Editable\Html
          label: Content
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_2
          editable: Supra\Editable\Html
          label: Content 2
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_3
          editable: Supra\Editable\Html
          label: Content 3
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content_4
          editable: Supra\Editable\Html
          label: Content 4
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: layout
          group: layout
          editable: Supra\Editable\SelectVisual
          label: Layout
          values:
            - id: column_1
              title: 1 column
              icon: icons/columns-1.png
            - id: column_2
              title: 2 columns
              icon: icons/columns-2.png
            - id: column_3
              title: 3 columns
              icon: icons/columns-3.png
            - id: column_4
              title: 4 columns
              icon: icons/columns-4.png
            - id: column_1_2_h
              title: 1+2 columns
              icon: icons/columns-1-2-h.png
            - id: column_2_1_h
              title: 2+1 columns
              icon: icons/columns-2-1-h.png
            - id: column_2_1_v
              title: 2+1 columns
              icon: icons/columns-2-1-v.png
            - id: column_1_2_v
              title: 1+2 columns
              icon: icons/columns-1-2-v.png
