- _use: Supra\Controller\Pages\Configuration

- Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Form\FormBlock
    title: Form
    icon: icon.png
    groupId: features
    description: Customizable form
    cmsClassname: Editable   
    properties:
      - Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          
      - Configuration\BlockPropertyConfiguration:
          name: email
          editable: Supra\Editable\String
          label: Send data to email
          
      - Configuration\BlockPropertyConfiguration:
          name: submit
          editable: Supra\Editable\String
          label: Button title
          default: Submit
          
      - Configuration\BlockPropertyConfiguration:
          name: confirmation_message
          editable: Supra\Editable\String
          label: Confirmation message
          default: Thank You!
          
      - Configuration\BlockPropertyConfiguration:
          name: error
          editable: Supra\Editable\String
          label: Empty field error message
          default: Please fill out this field
          
      - Configuration\BlockPropertyConfiguration:
          name: fields
          editable: Supra\Editable\PropertySet
          label: Fields

          properties:
            - Configuration\BlockPropertyConfiguration:
                name: title
                label: Field title
                editable: Supra\Editable\String
                default: Lorem ipsum
                
            - Configuration\BlockPropertyConfiguration:
                name: required
                editable: Supra\Editable\Checkbox
                label: Mandatory
                default: false
                
            - Configuration\BlockPropertyConfiguration:
                name: type
                editable: Supra\Editable\SelectList
                label: Type
                default: string
                values:
                  - id: string
                    title: String
                    icon: /components/FancyBlocks/Form/icons/type-string.png
                  - id: textarea
                    title: Text
                    icon: /components/FancyBlocks/Form/icons/type-text.png
                    
          additionalParameters:
            separateSlide: true
            labelAdd: Add field
            labelRemove: Remove field
            labelItem: "Field %s"
            labelButton: Manage fields
            
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: captcha
          editable: Supra\Editable\Checkbox
          label: Captcha
          default: false
          
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: captcha_label
          editable: Supra\Editable\String
          label: Captcha field title
          default: Captcha code
   ## Cache is mandatory for Blocks used in portal
    cache:
      Configuration\BlockControllerCacheConfiguration:
        enabled: true
        enabledByContext: __FormBlockCache
          
