- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: Sitemap
    groupId: system
    controllerClass: Project\Blocks\Sitemap\SitemapBlock
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        groups:
          - Supra\Controller\Pages