- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: News List
    groupId: features
    icon: icon.png
    class: Project\FancyBlocks\NewsList\NewsListBlock
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: newsApplication
          editable: Supra\Editable\Link
          label: News Application
