- Supra\Configuration\IncludeLoaderConfiguration:
    baseDir: ${__DIR__}
    files:
      - Gallery/config.yml
      - Languages/config.yml
      - Search/config.yml
      - Sitemap/config.yml
      - Text/config.yml
      - Logotype/config.yml
      - Menu/config.yml
      - Slideshow/config.yml
      - Tagline/config.yml
      - Promo/config.yml
      - Social/config.yml
      - Copyright/config.yml
      - Products/config.yml
      - NewsList/config.yml
      - NewsText/config.yml
      - BlogPost/config.yml
