- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\SlideshowAdvanced\SlideshowAdvancedBlock
    title: Advanced slideshow
    icon: icon.png
    groupId: features
    description: Description
    cmsClassname: Slideshow
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
          
    propertyGroups:
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: navigation
          type: sidebar
          icon: /cms/lib/supra/img/sidebar/icons/button-navigation.png
          label: Navigation
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: animation
          type: sidebar
          icon: /cms/lib/supra/img/sidebar/icons/button-animation.png
          label: Animation
    
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: navigation
          group: navigation
          editable: Supra\Editable\SelectVisual
          label: Navigation
          default: arrows
          values:
            - id: none
              title: None
              icon: icons/navigation/none.png
            - id: arrows
              title: Arrows
              icon: icons/navigation/arrows.png
            - id: dots
              title: Dots
              icon: icons/navigation/dots.png
            - id: progress
              title: Progress bar
              icon: icons/navigation/progress.png
          additionalParameters:
              iconStyle: center
              style: mid
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: scrollTimerEnabled
          group: animation
          editable: Supra\Editable\Checkbox
          label: Auto scroll
          description: Automatically goes from one slide to next after a delay
          default: 1
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: scrollTimerDelay
          group: animation
          editable: Supra\Editable\Number
          label: Auto scroll delay
          default: 5
          additionalParameters:
              minValue: 3
              maxValue: 10
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: animation
          group: animation
          editable: Supra\Editable\SelectVisual
          label: Animation
          values:
            - id: horizontal
              title: Horizontal slide
              icon: icons/animation/horizontal.png
            - id: vertical
              title: Vertical slide
              icon: icons/animation/vertical.png
            - id: fade
              title: Fade
              icon: icons/animation/fade.png
          additionalParameters:
              iconStyle: center
              style: mid
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: slides
          editable: Supra\Editable\Slideshow
          label: Slides
          # predefined Layout values
          values:
            ## layouts with text   
            - id: bg_text_left
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_left.html.twig
            - id: bg_text_right
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_right.html.twig
            - id: bg_text_center
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_center.html.twig
            ## layouts with media
            - id: bg_text_img_left
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_img_left.html.twig
            - id: bg_text_img_right
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_img_right.html.twig
            - id: bg_text_img_top
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_img_top.html.twig
            - id: bg_video
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_video.html.twig
              
          propertyGroups:
            - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
                id: advanced
                label: Advanced
                
          properties:
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: layout
                editable: Supra\Editable\SelectVisual
                label: Slide layout
                default: bg_text_img_left
                values:
                  - id: bg_text_left
                    title: Text on left side
                    icon: icons/layout/bg-text-left.png
                  - id: bg_text_right
                    title: Text on right side
                    icon: icons/layout/bg-text-right.png
                  - id: bg_text_center
                    title: Text in center
                    icon: icons/layout/bg-text-center.png
                  - id: bg_text_img_left
                    title: Text on left side
                    icon: icons/layout/bg-text-img-left.png
                  - id: bg_text_img_right
                    title: Text on right side
                    icon: icons/layout/bg-text-img-right.png
                  - id: bg_text_img_top
                    title: Text on top
                    icon: icons/layout/bg-text-img-top.png
                  - id: bg_video
                    title: Video
                    icon: icons/layout/bg-video.png
                additionalParameters:
                  style: mid
                  iconStyle: center
                  separateSlide: true
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: background
                editable: Supra\Editable\BlockBackground
                label: Background image
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: media
                editable: Supra\Editable\InlineMedia
                label: 
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: height
                editable: Supra\Editable\Number
                label: 
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: text_main
                editable: Supra\Editable\Html
                label: Main text
                default: <h1>Lorem ipsum</h1><br /><h2>Dolor sit amet</h2><p>Lid est laborum dolo es fugats untras. Et harums quidem rerum facilisdolores nemis omnis fugiats vitaro minimarerums unsers sadips dolores sitsers untra nemi amets.</p>
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: buttons
                editable: Supra\Editable\PropertySet
                label: Buttons
                properties:
                  - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                      name: overlay
                      label: Whole slide is linked
                      editable: Supra\Editable\Checkbox
                  - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                      name: title
                      label: Title
                      editable: Supra\Editable\String
                  - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                      name: link
                      label: Link
                      editable: Supra\Editable\Link
                additionalParameters:
                  separateSlide: true
                  labelAdd: Add more buttons
                  labelRemove: Remove button
                  labelItem: "Button %s"
                  labelButton: Set buttons
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: active
                editable: Supra\Editable\Checkbox
                label: Active
                default: true
                group: advanced
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: period_from
                editable: Supra\Editable\Date
                label: Published from
                group: advanced
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: period_to
                editable: Supra\Editable\Date
                label: Published till
                group: advanced