- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\SlideshowAdvanced\SlideshowAdvancedBlock
    title: Advanced slideshow
    icon: icon.png
    groupId: features
    description: Description
    cmsClassname: Slideshow
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
          
    propertyGroups:
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: design
          type: sidebar
          icon: /cms/lib/supra/img/toolbar/icon-design.png
          label: Design
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: animation
          type: sidebar
          icon: /cms/lib/supra/img/toolbar/icon-animation.png
          label: Animation
    
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: design
          group: design
          editable: Supra\Editable\SelectVisual
          label: Design
          default: arrows
          values:
            - id: none
              title: None
              icon: icons/design-none.png
            - id: arrows
              title: Arrows
              icon: icons/design-arrows.png
            - id: dots
              title: Dots
              icon: icons/design-dots.png
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: scrollTimerEnabled
          group: animation
          editable: Supra\Editable\Checkbox
          label: Auto scroll
          description: Automatically goes from one slide to next after a delay
          default: 1
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: scrollTimerDelay
          group: animation
          editable: Supra\Editable\Number
          label: Auto scroll delay
          default: 5
          additionalParameters:
              minValue: 3
              maxValue: 10
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: animation
          group: animation
          editable: Supra\Editable\SelectVisual
          label: Animation
          values:
            - id: horizontal
              title: Horizontal slide
              icon: icons/animation-horizontal.png
            - id: vertical
              title: Vertical slide
              icon: icons/animation-vertical.png
            - id: fade
              title: Fade
              icon: icons/animation-fade.png
          additionalParameters:
              iconStyle: center
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: slides
          editable: Supra\Editable\Slideshow
          label: Slides
          # predefined Layout values
          values:
            ## background image only
            - id: bg
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg.html
            ## layouts with text   
            - id: bg_text_left
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_left.html
            - id: bg_text_right
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_right.html
            ## layouts with media
            - id: bg_text_img_left
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_img_left.html
            - id: bg_text_img_right
              fileName: FancyBlocks/SlideshowAdvanced/templates/bg_text_img_right.html
          
          properties:
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: layout
                editable: Supra\Editable\SelectVisual
                label: Slide layout
                default: bg_text_img_left
                values:
                  - id: bg
                    title: Background image only
                    icon: icons/layout/bg.png
                  - id: bg_text
                    title: Background image and text
                    icon: icons/layout/bg-text.png
                    values:
                      - id: bg_text_left
                        title: Text on left side
                        icon: icons/layout/bg-text-left.png
                      - id: bg_text_right
                        title: Text on right side
                        icon: icons/layout/bg-text-right.png
                  - id: bg_text_img
                    title: Background image, text and graphics element
                    icon: icons/layout/bg-text-img.png
                    values:
                      - id: bg_text_img_left
                        title: Text on left side
                        icon: icons/layout/bg-text-img-left.png
                      - id: bg_text_img_right
                        title: Text on right side
                        icon: icons/layout/bg-text-img-right.png
                additionalParameters:
                    separateSlide: true
                    labelButton: Set layout
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: background
                editable: Supra\Editable\BlockBackground
                label: Background image
                additionalParameters:
                  labelButton: Set image
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: media
                editable: Supra\Editable\InlineMedia
                label: 
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: height
                editable: Supra\Editable\Number
                label: 
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: text_main
                editable: Supra\Editable\Html
                label: Main text
                default: <h1>Lorem ipsum</h1><h2>Dolor sit amet</h2><p>Lid est laborum dolo es fugats untras. Et harums quidem rerum facilisdolores nemis omnis fugiats vitaro minimarerums unsers sadips dolores sitsers untra nemi amets.</p>
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: text_top
                editable: Supra\Editable\Html
                label: Top text
                default: <p>Nascetur in mattis donec massa sed libero mauris congue at. Fames enim laoreet eget diam. Habitant nunc sed adipiscing malesuada feugiat viverra justo malesuada.</p>
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                name: buttons
                editable: Supra\Editable\PropertySet
                label: Buttons
                properties:
                  - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                      name: title
                      label: Title
                      editable: Supra\Editable\String
                  - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                      name: link
                      label: Link
                      editable: Supra\Editable\Link
                additionalParameters:
                  separateSlide: true
                  labelAdd: Add more buttons
                  labelRemove: Remove button
                  labelItem: "Button %s"
                  labelButton: Set buttons