- Supra\Router\Configuration\RouterConfiguration:
    url: { const: Project\SampleAuthentication\CONTROLLER_URL }
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Project\SampleAuthentication\AuthenticateController

- Supra\Router\Configuration\RouterConfiguration:
    url: { const: Project\SampleAuthentication\CONTROLLER_URL }
    priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Project\SampleAuthentication\AuthenticatePreFilterController
