- Supra\Controller\Configuration\ControllerConfiguration:
    router: 
      Supra\Router\Configuration\RouterConfiguration:
        url: { const: Project\SampleAuthentication\CONTROLLER_URL }
        controller: Project\SampleAuthentication\AuthenticateController

- Supra\Controller\Configuration\ControllerConfiguration:
    router: 
      Supra\Router\Configuration\RouterConfiguration:
        url: { const: Project\SampleAuthentication\CONTROLLER_URL }
        priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
        controller: Project\SampleAuthentication\AuthenticatePreFilterController
