- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Video\VideoBlock
    title: Video
    groupId: features
    description: Embeds video from popular video sharing websites.
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Lorem ipsum dolor sit amet
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: video
          editable: Supra\Editable\Video
          label: Paste the URL of a video or embed code
          description: Paste the URL of the video page on Youtube or Vimeo or paste the HTML embed code