- Supra\Configuration\IncludeLoaderConfiguration:
    baseDir: ${__DIR__}
    files:
      - Feedback/config.yml
      - Gallery/config.yml
      - Languages/config.yml
      - Login/config.yml
      - Search/config.yml
      - Sitemap/config.yml
      - Subscribe/config.yml
      - Text/config.yml
      - Form/config.yml
      - NewsList/config.yml
