- Supra\Controller\Configuration\ControllerConfiguration:
# TODO: should be controller config not config of the router
#    class: Project\Authentication\AuthenticationPreFilterController
    router: 
      Supra\Router\Configuration\RouterConfiguration:
        url: /cms
        priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
        controller: Supra\Cms\AuthenticationPreFilterController

- Supra\Controller\Configuration\ControllerConfiguration:
    router: 
      Supra\Router\Configuration\RouterConfiguration:
        url: /cms
        controller: Supra\Cms\CmsController

- Supra\Controller\Configuration\ControllerConfiguration:
    router: 
      Supra\Router\Configuration\RouterConfiguration:
        url: /cms/restore
        controller: Supra\Cms\InternalUserManager\Restore\RestoreController

- Supra\Cms\ApplicationConfiguration:
    id: Supra\Cms\ContentManager
    title: Pages
    icon: /cms/lib/supra/img/apps/content
    path: /cms/content-manager/
    authorizationAccessPolicy:
      Supra\Cms\ContentManager\ContentManagerAuthorizationAccessPolicy:
#       @TODO: Could assign this value from application configuration "id" parameter somehow
        applicationNamespace: Supra\Cms\ContentManager
  
- Supra\Cms\InternalUserManager\ApplicationConfiguration:
#   Assigned to controller because inside this namespace is password restore controller
    id: Supra\Cms\InternalUserManager\InternalUserManagerController
    title: Backoffice users
    path: /cms/internal-user-manager/
    icon: /cms/lib/supra/img/apps/internal-user
#   For development only
    allowGroupEditing: true
    authorizationAccessPolicy:
      Supra\Cms\InternalUserManager\InternalUserManagerAuthorizationAccessPolicy:
        applicationNamespace: Supra\Cms\InternalUserManager\InternalUserManagerController

- Supra\Cms\ApplicationConfiguration:
    id: Supra\Cms\BannerManager
    title: Banners
    path: /cms/banner-manager/
    icon: /cms/lib/supra/img/apps/banner
    authorizationAccessPolicy:
      Supra\Cms\BannerManager\BannerManagerAuthorizationAccessPolicy:
        applicationNamespace: Supra\Cms\BannerManager

- Supra\Cms\ApplicationConfiguration:
    id: Supra\Cms\MediaLibrary
    title: Media Library
    path: /cms/media-library/
    icon: /cms/lib/supra/img/apps/media_library
    authorizationAccessPolicy:
      Supra\Cms\MediaLibrary\MediaLibraryAuthorizationAccessPolicy:
        applicationNamespace: Supra\Cms\MediaLibrary
    
- Supra\Controller\Pages\Configuration\PageApplicationConfiguration:
    id: news
    className: Supra\Controller\Pages\News\NewsApplication
    
  
- Project\Payment\Paypal\Configuration:
    id: paypal_one
    url: /payment/paypal_one
    returnHost: http://supra7.krists.vig
    callbackHost: http://krists.videinfra.com
    iniSectionName: paypal_configuration_one
    collection: Project\Payment\DummyStore
    
    
- Project\Payment\Paypal\Configuration:
    id: paypal_two
    url: /payment/paypal_two
    returnHost: http://supra7.krists.vig
    callbackHost: http://krists.videinfra.com
    iniSectionName: paypal_configuration_two
    collection: Project\Payment\DummyStore
      