- Supra\Router\Configuration\RouterConfiguration:
    class: Supra\Router\TopPriorityRouter
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Supra\Locale\PreFilter\LocaleDetectorPreFilter

- Supra\Router\Configuration\RouterConfiguration:
    class: Supra\Router\TopPriorityRouter
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Supra\Controller\PreFilter\PostMaxSizeWorkaroundPreFilter
        
- Supra\Router\Configuration\RouterConfiguration:
    url: /
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Supra\Controller\Pages\PageController

#- Supra\Controller\Layout\Theme\Configuration\ThemeProviderConfiguration:
#   class: Supra\Controller\Layout\Theme\DefaultThemeProvider
#   isDefault: true
#   rootDir: webroot/themes
#   urlBase: /themes/