- Supra\Router\Configuration\RouterConfiguration:
    url: /dc
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Project\DistributedController\DistributedController