- _class: Supra\Controller\Pages\Configuration\BlockControllerConfiguration
  class: Project\AjaxContentBlock\AjaxContentBlock
  title: AjaxContentBlock
  groupId: system
  plugins:
    - _class: Supra\Controller\Pages\Plugin\BlockRequestPlugin
    # Need to implement feature to trigger automatically on load
#    - _class: Supra\Controller\Pages\Plugin\HtmlInjection
#      html:
#        js: |
#           <script type="text/javascript">$(function () { $.app.trigger('0072p4wt100woc0ww8oc'); });</script>
