- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Testimonials\TestimonialsBlock
    title: Testimonials
    icon: icon.png
    groupId: features
    description: Testimonials from customers
    cmsClassname: Gallery
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: What Clients Say
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: images
          editable: Supra\Editable\Gallery
          label: Images
          # each image item sub-properties
          properties:
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                 name: testimony
                 editable: Supra\Editable\Textarea
                 label: Testimony
                 default: Volutpat nunc aliquet amet duis duis ultrices egestas ac ipsum sit arcu ac sagittis consectetur id adipiscing eu
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                 name: name
                 editable: Supra\Editable\String
                 label: Name
                 default: Lorem Ipsum
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                 name: link
                 editable: Supra\Editable\Link
                 label: Link
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: navigation
          group: navigation
          editable: Supra\Editable\SelectVisual
          label: Navigation
          default: none
          values:
            - id: none
              title: None
              icon: icons/navigation-none.png
            - id: arrows
              title: Arrows
              icon: icons/navigation-arrows.png
            - id: arrows_pages
              title: Arrows with page number
              icon: icons/navigation-arrows-pages.png
          additionalParameters:
            style: mid