- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    controllerClass: Project\Blocks\Text\TextController
    title: Text
    groupId: system
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: false
        global: false
        groups:
          - Supra\Controller\Pages
          - Supra\FileStorage
        lifetime: 5 minutes
        