- Supra\Controller\Configuration\ControllerConfiguration:
    router: 
      Supra\Router\Configuration\RouterConfiguration:
        url: /dc
        controller: Project\DistributedController\DistributedController