- Supra\Configuration\IncludePhpConfiguration:
    files:
      - ${__DIR__}/config.php

- Supra\Router\Configuration\RouterConfiguration:
    url: { const: Project\SampleAuthentication\CONTROLLER_URL }
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Project\SampleAuthentication\SampleAuthenticationController

- Supra\Router\Configuration\RouterConfiguration:
    url: { const: Project\SampleAuthentication\CONTROLLER_URL }
    priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Project\SampleAuthentication\SampleAuthenticationPreFilter
