- Supra\Controller\Configuration\ControllerConfiguration:
# TODO: should be controller config not config of the router
#    class: Project\Authentication\AuthenticationPreFilterController
    router: 
      Supra\Router\Configuration\RouterConfiguration:
        url: /cms
        priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
        controller: Project\Authentication\AuthenticationPreFilterController
# TODO: realize such configuration
#    loginPath: /cms/login
#    basePath: /cms
#    loginField: supra_login
#    passwordField: supra_password
# Points to the namespace to be used (maybe)
#    securedNamespace: Supra\Cms
        
# TODO: remove this configuration
#- Supra\Session\Configuration\SessionNamespaceConfiguration:
#    managerNamespace: Project\Authentication
#    name: Cms
#    class: Project\Authentication\AuthenticationSessionNamespace
#    namespaces: 
#      - Project\Authentication
#      - Supra\Cms