- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\BlogPost\BlogPostBlock
    title: Blog post
    groupId: blog
    description: A blog post with the option of adding a main illustration – graphics or video that would be used for a blog roll and latest posts section.
    cmsClassname: Editable
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
        lifetime: 60 seconds
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: description
          editable: Supra\Editable\Textarea
          label: Short description
          description: Will show as preview 
          default: Volutpat nunc aliquet amet duis duis ultrices egestas ac ipsum sit arcu ac sagittis consectetur id adipiscing eu
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: tags
          editable: Supra\Editable\PageKeywords
          label: Tags
          description: Use comma, semicolon or return key to separate tags 
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: media
          editable: Supra\Editable\InlineMedia
          label: Main illustration
          description: Will show with this post's preview
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: content
          editable: Supra\Editable\Html
          label: Content
          default: |
                   <h2>Est ultrices sed in tristique sollicitudin sit</h2>
                   <p>Leo velit odio massa nullam id ut at. Interdum donec ultrices vitae feugiat at amet sollicitudin. Et duis in vitae nisi eu nunc quisque id et molestie. Adipiscing vitae, amet maecenas massa non at eu mi convallis. Vitae interdum in dui pharetra turpis. Pellentesque habitasse morbi consectetur pretium adipiscing. Quis elementum fermentum tincidunt imperdiet semper vitae malesuada pellentesque in interdum. Nisl nec nisl, mollis sed felis nisl risus diam eu condimentum. Eget id congue augue gravida et, facilisis venenatis mauris pharetra. Mauris eget arcu accumsan, amet, vitae leo quis pretium, libero. Risus molestie ut imperdiet vel ornare sed velit proin in nibh. Sit ac eget vel lacus, viverra. Sem dignissim nullam condimentum elit. Auctor quis quis velit, amet, pulvinar hendrerit in porttitor turpis.</p>
                   <h3>Id egestas amet turpis massa viverra lectus</h3>
                   <p>Mattis mauris massa urna, suspendisse semper ornare. Felis, mattis pharetra risus vitae pharetra, ullamcorper vulputate sapien at. Volutpat aenean quam magna justo augue quis gravida. Dui rhoncus duis massa condimentum nulla. Viverra risus, eget imperdiet pellentesque. Habitasse dictum auctor faucibus amet quis lectus fames lorem. Sed vulputate mattis imperdiet nunc, ac vitae. Mi neque porttitor non tellus sit est purus. Augue nec id accumsan vitae nunc sagittis, quam in eu. Arcu enim, libero neque condimentum augue etiam rhoncus purus. Eu fusce neque sapien quam et neque imperdiet condimentum sed quis.</p>
                   <ul>
                     <li>Massa tristique consequat in diam sem penatibus lectus</li>
                     <li>Nisl sed viverra quis porttitor massa sit fames pellentesque</li>
                     <li>Bibendum risus purus nunc imperdiet enim</li>
                   </ul>
      