- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Social\SocialBlock
    title: Links to social pages
    icon: icon.png
    groupId: features
    description: Allows you to link your pages in social networks. Useful for a footer or similar contact info related areas.
    cmsClassname: Editable
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
