- Supra\Router\Configuration\RouterConfiguration:
    url: /
    priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Project\Blocks\Login\LoginPreFilterController

- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: Login
    groupId: system
    class: Project\Blocks\Login\LoginBlock
    description: Frontend login page block
    cmsClassname: Editable
    icon: icon.png
