- Supra\Router\Configuration\RouterConfiguration:
    url: /
    priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
    controller:
      Supra\Controller\Configuration\ControllerConfiguration:
        class: Project\Blocks\Login\LoginPreFilterController

- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: Login
    groupId: system
    class: Project\Blocks\Login\LoginBlock
    description: Frontend login page block
    cmsClassname: Editable
    icon: icon.png
    propertyGroups:
      - Supra\Controller\Pages\Configuration\BlockPropertyGroupConfiguration:
          id: labels
          type: top
          label: Labels
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: loginLabel
          editable: Supra\Editable\String
          label: Login label
          default: Login
          group: labels
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: passwordLabel
          editable: Supra\Editable\String
          label: Password label
          default: Password
          group: labels
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: loginButtonLabel
          editable: Supra\Editable\String
          label: Login button label
          default: Login
          group: labels
