- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\TwitterFeed\TwitterFeedBlock
    title: Twitter Feed
    icon: icon.png
    groupId: features
    description: Display Twitter feeds from specific account
    cmsClassname: Editable
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: account
          editable: Supra\Editable\String
          label: Twitter account name
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: limit
          editable: Supra\Editable\Number
          label: Number of tweets
          default: 5
          additionalParameters:
              minValue: 1
              maxValue: 30
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: follow
          editable: Supra\Editable\Checkbox
          label: Show follow button
          default: 1