- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\Blocks\Gallery\GalleryBlock
    title: Gallery Block
    groupId: system
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    cmsClassname: Gallery
    icon: icon.png
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          # becase has shared properties
          - Supra\Controller\Pages
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: design
          editable: Supra\Editable\SelectVisual
          label: Design
          values:
            - id: vertical
              title: Vertical
              icon: icons/vertical.png
            - id: horizontal
              title: Horizontal
              icon: icons/horizontal.png
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: images
          editable: Supra\Editable\Gallery
          label: Images
          shared: true
          # each image item sub-properties
          properties:
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                 name: title
                 editable: Supra\Editable\String
                 label: Title
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                 name: description
                 editable: Supra\Editable\Textarea
                 label: Description
            - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
                 name: link
                 editable: Supra\Editable\Link
                 label: Link