- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Languages\LanguageSelectorBlock
    title: Language Selector
    groupId: system
    description: 
    cmsClassname: Editable
    icon: icon.png 
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Select language