- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Menu\MenuBlock
    title: Menu
    icon: icon.png
    groupId: features
    description: Description
    cmsClassname: Editable
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        global: false
        groups:
          - Supra\FileStorage
          - Supra\Controller\Pages

- Supra\Configuration\IncludeLoaderConfiguration:
    baseDir: ${__DIR__}
    files:
      - Footer/config.yml
      
- Supra\Configuration\IncludeLoaderConfiguration:
    baseDir: ${__DIR__}
    files:
      - Left/config.yml      