- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: Feedback form
    groupId: system
    controllerClass: Project\Feedback\FeedbackBlock
    description: Feedback form
    cmsClassname: Editable