- _version: 2

- _class: Supra\Controller\Pages\Configuration\BlockControllerConfiguration
  class: Project\Blocks\Unique\UniqueBlock
  unique: true
  title: Unique block
  groupId: system
  description: Unique block - only one instance of this block can exist on page
  cmsClassname: Editable
  icon: icon.png