- _class: Supra\Form\Configuration\FormBlockControllerConfiguration
  class: Project\Blocks\Form\FormBlock
  title: Form Block
  groupId: features
  description: Description
  cmsClassname: Editable
#  cache:
#    Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
#      enabled: true
#      global: false
#      groups:
#        - Supra\FileStorage
#        - Supra\Controller\Pages
  dataClass: Project\Blocks\Form\Entity\Form
#  plugins:
#    - _class: Supra\Controller\Pages\Plugin\BlockFormRequestPlugin
