- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    controllerClass: Project\Blocks\Languages\LanguageSelectorBlock
    title: Language Selector
    groupId: system
    description: 
    cmsClassname: Editable
    icon: icon.png