- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: Feedback form
    groupId: system
    class: Project\Blocks\Feedback\FeedbackBlock
    description: Feedback form
    cmsClassname: Editable
    icon: icon.png
