- _class: Supra\Cms\ContentManager\ApplicationConfiguration
  id: Supra\Cms\ContentManager
  title: Pages
  icon: /cms/lib/supra/img/apps/pages
  url: content-manager
  allowLimitedPageOption: true
  galleryBlockId: Project\Blocks\Gallery\GalleryBlock
  htmlEditorPlugins:
    fonts: true
    table-mobile: true
  authorizationAccessPolicy:
    _class: Supra\Cms\ContentManager\ContentManagerAuthorizationAccessPolicy
#   @TODO: Could assign this value from application configuration "id" parameter somehow
    applicationNamespace: Supra\Cms\ContentManager