- _class: Supra\Cms\InternalUserManager\ApplicationConfiguration
# Assigned to controller because inside this namespace is password restore controller
  id: Supra\Cms\InternalUserManager\InternalUserManagerController
  title: Backoffice Users
  url: internal-user-manager
  icon: /cms/lib/supra/img/apps/backoffice_users
  sortIndex: 400
  authorizationAccessPolicy:
    _class: Supra\Cms\InternalUserManager\InternalUserManagerAuthorizationAccessPolicy
    applicationNamespace: Supra\Cms\InternalUserManager\InternalUserManagerController

# - _class: Supra\Cms\ApplicationConfiguration
  # id: Supra\Cms\BannerManager
  # title: Banners
  # url: banner-manager
  # icon: /cms/lib/supra/img/apps/banners
  # authorizationAccessPolicy:
    # _class: Supra\Cms\BannerManager\BannerManagerAuthorizationAccessPolicy
    # applicationNamespace: Supra\Cms\BannerManager

- _class: Supra\Cms\ApplicationConfiguration
  id: Supra\Cms\AuditLog
  title: Audit log
  url: audit-log
  icon: /cms/lib/supra/img/apps/audit
  sortIndex: 500
  authorizationAccessPolicy:
    _class: Supra\Cms\AuditLog\AuditLogAuthorizationAccessPolicy
    applicationNamespace: Supra\Cms\AuditLog

- _class: Supra\Cms\ApplicationConfiguration
  id: Supra\Cms\Dashboard
  title: Dashboard
  hidden: true
  url: dashboard
  icon: /cms/lib/supra/img/apps/dashboard
  sortIndex: 300
#  authorizationAccessPolicy:
#    _class: Supra\Cms\Dashboard\DashboardAuthorizationAccessPolicy
#    applicationNamespace: Supra\Cms\Dashboard

#- _class: Supra\Cms\ApplicationConfiguration
#  id: Supra\Cms\Settings
#  title: Settings
#  url: settings
#  icon: /cms/lib/supra/img/apps/settings
#  authorizationAccessPolicy:
#    _class: Supra\Cms\Settings\SettingsAuthorizationAccessPolicy
#    applicationNamespace: Supra\Cms\Settings

- _class: Supra\Cms\BlogManager\ApplicationConfiguration
  id: Supra\Cms\BlogManager
  title: Blog
  url: blog-manager
  icon: /cms/lib/supra/img/apps/blog
  sortIndex: 200
  authorizationAccessPolicy:
    _class: Supra\Cms\BlogManager\BlogManagerAuthorizationAccessPolicy
    applicationNamespace: Supra\Cms\BlogManager

- _class: Supra\Cms\MediaLibrary\ApplicationConfiguration
  id: Supra\Cms\MediaLibrary
  title: Files
  url: media-library
  icon: /cms/lib/supra/img/apps/media_library
  sortIndex: 300

##possible values: "full", "partial" and "none"
## - "none" will disable any existence check
## - "partial" will force to check only when tab with file info is displayed
## - "full" will force to check file existence also when complete list of files is displayed
##default is "none"
  checkFileExistence: full
  knownFileExtensions:
    - pdf
    - xls
    - xlsx
    - doc
    - docx
    - swf
  authorizationAccessPolicy:
    _class: Supra\Cms\MediaLibrary\MediaLibraryAuthorizationAccessPolicy
    applicationNamespace: Supra\Cms\MediaLibrary

#- Supra\Cms\CrudManager\ApplicationConfiguration:
#    id: Supra\Cms\CrudManager
#    title: Branches Manager
#    url: crud-manager
#    icon: /cms/lib/supra/img/apps/media_library
#    entity: fill the entity name here
#    authorizationAccessPolicy:
#      Supra\Cms\CrudManager\CrudManagerAuthorizationAccessPolicy:
#        applicationNamespace: Supra\Cms\CrudManager

# - _class: Supra\Controller\Pages\Configuration\PageApplicationConfiguration
  # id: news
  # className: Supra\Controller\Pages\News\NewsApplication
  # title: News
  # icon: /cms/content-manager/sitemap/images/apps/news.png
  # newChildrenFirst: true

# - _class: Supra\Controller\Pages\Configuration\PageApplicationConfiguration
  # id: glossary
  # className: Supra\Controller\Pages\Glossary\GlossaryApplication
  # title: Glossary
  # icon: /cms/content-manager/sitemap/images/apps/forum.png
  # newChildrenFirst: true

- _class: Supra\Controller\Pages\Configuration\PageApplicationConfiguration
  id: blog
  className: Supra\Controller\Pages\Blog\BlogApplication
  title: Blog
  icon: /cms/content-manager/sitemap/images/apps/forum.png
  newChildrenFirst: true
  
# Implement this configuration to project-specific location if needed
#- Supra\BannerMachine\Configuration\ProviderConfiguration:
#    id: banner-machine-one
#    redirectorPath: /banner-machine-one
#    types:
#      - Supra\BannerMachine\Configuration\BannerType\DefaultSizeTypeConfiguration:
#          id: square
#          name: Square (215 x 246)
#          width: 215
#          height: 246
#          ratioDelta: 0.1
#      - Supra\BannerMachine\Configuration\BannerType\DefaultSizeTypeConfiguration:
#          id: wide
#          name: Wide (952 x 130)
#          width: 952
#          height: 130
#          ratioDelta: 0.1

- _class: Supra\Controller\Pages\Configuration\BlockControllerConfiguration
  title: Broken block
  groupId: system
  hidden: true
  class: Supra\Controller\Pages\BrokenBlockController

- _class: Supra\Event\EventConfiguration
  listener: Supra\Authentication\Listener\BruteForceAuthenticationAttackProtector

#- Supra\Cms\CrudManager\ApplicationConfiguration:
#    id: Supra\Cms\LocaleManager\LocaleManager
#    title: Locales
#    url: locale-manager
#    entity: Supra\Locale\Entity\Locale
#    icon: /cms/lib/supra/img/apps/settings
#    classname: Supra\Cms\LocaleManager\LocaleManager
#    authorizationAccessPolicy:
#      Supra\Cms\CrudManager\CrudManagerAuthorizationAccessPolicy:
#        applicationNamespace: Supra\Cms\CrudManager

