- _use: Supra\Router\Configuration\RouterConfiguration
- _use: Supra\Controller\Configuration\ControllerConfiguration


- _class: Supra\Configuration\ConstantConfiguration
  name: SUPRA_CMS_URL
  value: cms
- _class: RouterConfiguration
  url: { const: SUPRA_CMS_URL }
  priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
  controller:
    _class: ControllerConfiguration
    class: SupraSite\Cms\SecureAccessPreFilter
  objectRepositoryCaller: Supra\Cms\CmsController

- _class: RouterConfiguration
  url: { const: SUPRA_CMS_URL }
  priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
  controller:
    _class: Supra\Locale\PreFilter\LocalePreFilterControllerConfiguration
    class: Supra\Locale\PreFilter\LocaleDetectorPreFilter
    detectInactiveLocales: true
  objectRepositoryCaller: Supra\Cms\CmsController

- _class: RouterConfiguration
  url: { const: SUPRA_CMS_URL }
  priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
  controller:
    _class: ControllerConfiguration
    class: Supra\Cms\AuthenticationPreFilterController

- _class: RouterConfiguration
  url: /
  priority: { const: Supra\Router\RouterAbstraction::PRIORITY_TOP }
  controller:
    _class: ControllerConfiguration
    class: Supra\Controller\Pages\ThemePreviewPreFilterController

- _class: RouterConfiguration
  url: { const: SUPRA_CMS_URL }
  controller:
    _class: ControllerConfiguration
    class: Supra\Cms\CmsController
