- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: Sitemap
    icon: icon.png
    groupId: system
    class: Project\FancyBlocks\Sitemap\SitemapBlock
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        groups:
          - Supra\Controller\Pages
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Sitemap