- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    title: Sitemap
    groupId: system
    class: Project\FancyBlocks\Sitemap\SitemapBlock
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
        enabled: true
        groups:
          - Supra\Controller\Pages