- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Menu\Left\LeftMenuBlock
    title: Side menu
    icon: left_menu.png
    groupId: features
    description: Places a menu in the sidebar and allows you to create a select-box (drop-down menu).
    cmsClassname: Editable
    cache:
      Supra\Controller\Pages\Configuration\BlockControllerCacheConfiguration:
      enabled: true
      global: false
      groups:
        - Supra\FileStorage
        - Supra\Controller\Pages
        
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
         name: menuLabel
         editable: Supra\Editable\String
         label: Title
         default: Menu
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
         name: rootLink
         editable: Supra\Editable\Link
         label: Menu Root
