- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\Menu\Left\LeftMenuBlock
    title: Left Menu Block
    groupId: features
    description: Sweet Left Menu Block
    cmsClassname: Editable
    properties:
      - Supra\Controller\Pages\Configuration\BlockPropertyConfiguration:
         name: rootLink
         editable: Supra\Editable\Link
         label: Menu Root
         shared: false
