- _use: Supra\Controller\Pages\Configuration

- Configuration\BlockControllerConfiguration:
    class: Project\FancyBlocks\BlogTags\BlogTagsBlock
    title: Blog tags
    icon: icon.png
    groupId: blog
    description: A side-menu that allows visitors to filter blog posts by tags.
    cmsClassname: Editable   
    properties:
      - Configuration\BlockPropertyConfiguration:
          name: block_title
          editable: Supra\Editable\String
          label: Title
          default: Tags
      - Configuration\BlockPropertyConfiguration:
          name: popular_title
          editable: Supra\Editable\String
          label: Popular tags
          default: Popular
      - Configuration\BlockPropertyConfiguration:
          name: all_title
          editable: Supra\Editable\String
          label: All tags
          default: All
      - Configuration\BlockPropertyConfiguration:
          name: clear_title
          editable: Supra\Editable\String
          label: Clear tags
          default: Clear tags
      - Configuration\BlockPropertyConfiguration:
          name: blog_page
          editable: Supra\Editable\Link
          label: Blog page