- Supra\Search\SearchControllerConfiguration:
    resultsTemplateFilename: search-results.html.twig
    noResultsTemplateFilename: search-results-empty.html.twig
    controllerClass: Project\Search\ProjectSearchController
    resultsPerPage: 10
    title: Unified search block
    description: Unified search block
