- Supra\Search\SearchControllerConfiguration:
    formTemplateFilename: search/search-form.html.twig
    resultsTemplateFilename: search/search-results.html.twig
    noResultsTemplateFilename: search/search-results-empty.html.twig
    resultsPerPage: 10
