- Supra\Search\SearchControllerConfiguration:
    resultsTemplateFilename: template/search/search-results.html.twig
    noResultsTemplateFilename: template/search/search-results-empty.html.twig
    resultsPerPage: 2
