- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    controllerClass: Project\Search\SearchController
    title: Search!!!
    description: Search search search search!
    cmsClassname: Editable