- Supra\BannerMachine\Configuration\ProviderConfiguration:
    id: banner-machine-one
    redirectorPath: /banner-machine-one
    types: 
      - Supra\BannerMachine\Configuration\BannerType\DefaultSizeTypeConfiguration:
          id: square
          name: Square (215 x 246)
          width: 215
          height: 246
          ratioDelta: 0.1
      - Supra\BannerMachine\Configuration\BannerType\DefaultSizeTypeConfiguration:
          id: wide
          name: Wide (952 x 130)
          width: 952
          height: 130
          ratioDelta: 0.1

- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    class: Supra\BannerMachine\BannerMachineController
    title: Banner
    groupId: system
    description: It's a banner.
    cmsClassname: Editable
    iconWebPath: /components/BannerMachine/icon.png