- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    controllerClass: Supra\BannerMachine\BannerMachineController
    title: Banner
    groupId: system
    description: It's a banner.
    cmsClassname: Editable