- Supra\Controller\Pages\Configuration\BlockControllerConfiguration:
    controllerClass: Supra\BannerMachine\BannerMachineController
    title: Banner
    description: It's a banner.
    cmsClassname: Editable